# Generated by Django 5.0.3 on 2024-11-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keypoints',
            name='content',
            field=models.TextField(blank=True, help_text='Key points or brief answers related to past questions'),
        ),
        migrations.AlterField(
            model_name='pastquestions',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='practiceexplanations',
            name='explanation',
            field=models.TextField(help_text='Explanation for the correct answer in CBT'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
